version: "3.8"

services:

  app:

    image: oscarin18/proyectof:1.0

    ports:
      - "8080:8080"

    depends_on:
      - mysql


  mysql:

    image: mysql:8.0

    environment:

      MYSQL_DATABASE: personas_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"